### ISSUE TITLE
Unable to upload to new project

### ISSUE THREAD

**Issue by sremedios** [VUIIS/dax#247] opened 2020-04-24 14:05 UTC
I've created a new project `CQS_TBI_seg` but am unable to see it with `Xnatreport -p CQS_TBI_seg` or `Xnatupload -c mycsvfile.csv` with target project `CQS_TBI_seg`.

Here are some screenshots.

![image](https://user-images.githubusercontent.com/22140920/80221304-b30d2700-860a-11ea-9fca-a03fc2f12607.png)

![image](https://user-images.githubusercontent.com/22140920/80221325-bacccb80-860a-11ea-84ba-a46c5155569d.png)

**Comment by bud42** [comment] 2020-05-14 16:50
This was discussed and resolved in the VUIIS internal forum. The cause was a project alias that matched a project name. Previously this was not a problem, but something changed in a recently applied XNAT update.

**Closed by bud42** 2020-05-14 16:50 UTC
